name: backend_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.8.0

dev_dependencies:
  very_good_analysis: ^9.0.0
