name: mobile_client
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  app_ui: ^0.1.0
  backend_repository: ^0.1.0
  bloc: ^9.0.0
  domain: ^0.1.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1
  intl: ^0.20.2
  meta: ^1.16.0
  mobile_scanner: ^7.0.1

dev_dependencies:
  very_good_analysis: ^9.0.0

flutter:
  generate: true
  uses-material-design: true
