name: app_ui
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  domain: ^0.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^9.0.0

flutter:
  assets:
    - assets/images/art_cards/
    - assets/images/